### ISSUE TITLE
Wordmark missing on work-template

### ISSUE THREAD

**Issue by devonash** [devonash/portfolio#12]
The wordmark image is not showing on the work-template pages when synced to github.
![screen shot 2015-11-19 at 2 58 22 am](https://cloud.githubusercontent.com/assets/6373210/11265338/83f150ec-8e69-11e5-8905-0c435d3c033a.png)

@thomasjbradley

**Comment by thomasjbradley** [comment]
I think it's just missing the `{{site.baseurl}}` in front of the `<img src="">`.

**Comment by devonash** [comment]
Thankyou!
