### ISSUE TITLE
Vimeo video disappears on small mobile screens

### ISSUE THREAD

**Issue by devonash** [devonash/portfolio#14]
I'm not sure if It's a media query problem or if it's something to do with the video? 

![screen shot 2016-01-19 at 11 10 44 pm](https://cloud.githubusercontent.com/assets/6373210/12439748/4acdf198-bf02-11e5-8b0f-997d09497236.png)
![screen shot 2016-01-19 at 11 12 25 pm](https://cloud.githubusercontent.com/assets/6373210/12439747/4aca8cec-bf02-11e5-811d-dca5a85a4305.png)

@thomasjbradley

**Comment by thomasjbradley** [comment]
I think it's because the grid `.unit` tags are missing the `xs` size.

**Comment by devonash** [comment]
It worked! Thanks for the help Thomas!
