### ISSUE TITLE
Arrow Keys Overlap Home (Safari 9)

### ISSUE THREAD

**Issue by valeriebordeleau** [devonash/portfolio#2]
![screen shot 2015-10-08 at 9 03 05 am](https://cloud.githubusercontent.com/assets/6373198/10366936/81eba610-6d9b-11e5-9cce-12600a1b2af3.png)

The Arrow Keys overlap your Home icon on your project page

**Comment by valeriebordeleau** [comment]
Perhaps try position absolute and fiddle with the position?

**Comment by malo0140** [comment]
Safari on Ipad has the same problem.

**Comment by kayleemenard** [comment]
For firefox on netflix, there was a similar issue. I suggest playing around by spacing them using percentages, I think that giving it a position would break it on different devices and different views. There's also the option of placing them in their own grid so each share 1/3 or the screen width, then all you'd have to do it center them.

<img width="443" alt="screen shot 2015-10-08 at 9 56 13 am" src="https://cloud.githubusercontent.com/assets/6373202/10368402/068c843c-6da3-11e5-8cdf-9702b0f0254a.png">
